# Generated by Django 3.0.3 on 2020-02-18 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(max_length=24)),
                ('location', models.CharField(max_length=150)),
                ('job', models.CharField(choices=[('1', 'Безработный'), ('2', 'Студент'), ('3', 'Работник')], max_length=24)),
                ('position', models.CharField(choices=[('1', 'IT'), ('2', 'BA/ECO'), ('3', 'IR'), ('4', 'LNG'), ('5', 'CHN'), ('6', 'LAW'), ('7', 'Другое')], max_length=24)),
                ('created_date', models.DateTimeField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_description', models.CharField(max_length=300)),
                ('email', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
